#!/bin/zsh
# Chunk file into fifo

LINES=`cat $1 |wc -l`
gran=40
for curr in `seq $gran $gran $LINES`
do
  echo $curr
  ( head -n $curr $1 |tail -n $gran > $2; )
done
echo $LINES
( tail -n $(($LINES-$curr)) $1 > $2; )
