#!/bin/zsh

date=`date`
echo "$date ==="; echo "$date ===" >&2
for user in ~/ranga ~/rebecca ~/akkartik
do
  lockfile=/tmp/`basename $user`.lock
  outfile=/tmp/`basename $user`.`date +"%Y-%m-%d-%H-%M-%S"`
  if [ ! -f /tmp/`basename $user`.lock ]
  then
    touch $lockfile
    echo "`date` $user ($date)"; echo "`date` $user ($date)" >&2
    cd $user
    ./crawl_feeds > $outfile 2> $outfile.err

    rsync -avz --delete $user /app/pair0
    rm $lockfile
  else
    echo "`date` skipping $user ($date)"
  fi
done
