#!/bin/zsh

DIR=test/fixtures/htmlclean/unsorted
FILELIST=`ls $DIR |grep "\.metadata$" |shuffle |perl -pwe 's/\.metadata$//'`

idx=0
for file in `echo $FILELIST`
do
  echo $idx $file
  idx=$(($idx+1))
  file=$DIR/$file
  open -a firefox `python metadata.py $file.metadata url`
  open -a firefox $file.clean
  echo "good?"
  read response
  if [[ $response == 'y'* ]]
  then
    echo Y
    mv $file.* test/fixtures/htmlclean/correct
  elif [[ $response == 'n'* ]]
  then
    echo X
    mv $file.* test/fixtures/htmlclean/wrong
  elif [[ $response == 'l'* ]]
  then
    echo Loose
    mv $file.* test/fixtures/htmlclean/loose
  fi
done
