#!/bin/zsh

DIR=test/fixtures/clean/unsorted
FILELIST=`ls $DIR |grep "\.metadata$" |shuffle |perl -pwe 's/\.metadata$//'`

idx=0
for file in `echo $FILELIST`
do
  echo $idx $file
  idx=$(($idx+1))
  file=$DIR/$file
  open -a firefox `python metadata.py $file.metadata url`
  open -a firefox $file.clean
  vi $file.raw $file.clean
  mv $file.* test/fixtures/clean -i
done
