#!/bin/zsh

export PYTHONPATH=$PYTHONPATH:/app/local/share/lib/python

cd ~/readwarp

mkdir -p urls fifos
for stage in crawl clean gc
do
  if [ ! -p fifos/$stage ]; then mkfifo fifos/$stage; fi
done

while true
do
  python crawl.py
done
