#!/bin/zsh

export PYTHONPATH=$PYTHONPATH:/app/local/share/lib/python

cd ~/readwarp

mkdir -p urls fifos
for stage in crawl clean mdata index
do
  if [ ! -p fifos/$stage ]; then mkfifo fifos/$stage; fi
done

lockfile=/tmp/readwarp.lock
if [ ! -f $lockfile ]
then
  echo "=== `date`"
  touch $lockfile
  python crawl.py

  rm $lockfile
fi
