#!/usr/bin/zsh

export PATH=.:/app/local/0bin:/app/local/share/scripts:/app/local/share/scripts/Startup:$PATH:/usr/sbin

cd ~/readwarp
{
  echo "New sessions"
  grep "||" $(ls www/logs/srv-* |sort |tail -n2 |head -n1) |grep "nil)" |column 2 |sort |uniq |wc -l

  wget http://readwarp.com/rusers -O -

  echo
  wget http://readwarp.com/votingstats -O -

  echo; echo
  wget http://readwarp.com/cleardailystats -O -
  for i in feedback/*
  do
    echo "== $i"
    cat $i
  done
} |sendmail -f feedback@readwarp.com akkartik@gmail.com

rm feedback/*
