#!/bin/zsh

if [ $# -gt 0 ]
then
  ab -n100 -c15 -C user=test-user-cookie "http://readwarp.com/docupdate?doc=a&sname=global&outcome=1"
else
  wget "http://127.0.0.1:8080/settest?u=0jliDbJi"
  ab -n100 -c10 -C user=rvA1z1R0 "http://127.0.0.1:8080/docupdate?doc=a&sname=yjXSoFTq&outcome=1"
fi
